### PR TITLE
Update deps and added adaptive icon

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Hi @theScrabi,

i added adaptive icons to your app similar to [Notes](https://github.com/stefan-niedermann/nextcloud-notes/commit/6368ef06c6598b384b901ebb4b6832ac7cad2b31), [News](https://github.com/nextcloud/news-android/pull/628), [OCReader](https://github.com/schaal/ocreader/pull/82), [Phone Sync](https://github.com/nerzhul/ownCloud-SMS-App/pull/188) and [(soon) Files](https://github.com/nextcloud/android/issues/2444#issuecomment-379911794) android clients.

I hope, that all the Nextcloud apps in the ecosystem out there can have somewhen in the future a similar look and feel.

Here are some screenshots of what it would look like:

screenshot_1523620995
screenshot_1523621005
screenshot_1523621018

Regards

### CODE REVIEW

**Comment by theScrabi** [comment]
@stefan-niedermann would you mind please adding an adaptive Icon to ownCloud as well? You can simply do this by setting the typical owncloud color as background.

**Comment by stefan-niedermann** [comment]
sure, but it might take some days, i am currently busy :)

**Comment by stefan-niedermann** [comment]
Okay @theScrabi can you have another look please? I created the adaptive icon for ownCloud as well with the typical ownCloud color as background.

Where do you use the /assets folder by the way? Can it be removed or are you still using it? (I could not find any references from the source code)

**Comment by theScrabi** [comment]
Thank you for your submission.

assets is used outside the project for hosting the source files for the launcher icons. Please keep it.

**Comment by stefan-niedermann** [comment]
I just thought about updating the Nextcloud icons to use the new background (the blue one with the withe dots)

**Comment by theScrabi** [comment]
Yes you can do that :D

**Pull request merged**
